; Generated by PSoC Designer 5.0.1127.0
;
include "m8c.inc"
;  Personalization tables 
export LoadConfigTBL_usb_ir_loader
AREA psoc_config(rom, rel)
LoadConfigTBL_usb_ir_loader:
	M8C_SetBank0
;  Global Register values Bank 0
	mov	reg[32h], 00h		; CLKIOCR register (CLKIOCR)
	mov	reg[30h], 00h		; CPUCLKCR register (CPUCLKCR)
	mov	reg[05h], 00h		; P00CR register (P00CR)
	mov	reg[06h], 00h		; P01CR register (P01CR)
	mov	reg[07h], 00h		; P02CR register (P02CR)
	mov	reg[08h], 00h		; P03CR register (P03CR)
	mov	reg[09h], 00h		; P04CR register (P04CR)
	mov	reg[0ah], 00h		; P05CR register (P05CR)
	mov	reg[0bh], 00h		; P06CR register (P06CR)
	mov	reg[0ch], 00h		; P07CR register (P07CR)
	mov	reg[0dh], 00h		; P10CR register (P10CR)
	mov	reg[0eh], 00h		; P11CR register (P11CR)
	mov	reg[0fh], 00h		; P12CR register (P12CR)
	mov	reg[10h], 00h		; P13CR register (P13CR)
	mov	reg[11h], 00h		; P14CR register (P14CR)
	mov	reg[12h], 00h		; P15CR register (P15CR)
	mov	reg[13h], 00h		; P16CR register (P16CR)
	mov	reg[14h], 00h		; P17CR register (P17CR)
	mov	reg[15h], 00h		; P20CR register (P20CR)
	mov	reg[16h], 00h		; P30CR register (P30CR)
	mov	reg[3dh], 00h		; SPICR register (SPICR)
	mov	reg[2bh], 00h		; TCAPINTE register (TCAPINTE)
	mov	reg[31h], 80h		; TMRCLKCR register (TMRCLKCR)
	mov	reg[2ah], 00h		; TMRCR register (TMRCR)
	mov	reg[73h], 00h		; VREGCR register (VREGCR)
;  Instance name USB, User Module USB
	M8C_SetBank1
;  Global Register values Bank 1
	mov	reg[e0h], 03h		; OscillatorControl_0 register (OSC_CR0)
	mov	reg[e3h], 14h		; VLDCR register (VLDCR)
;  Instance name USB, User Module USB
	M8C_SetBank0
;  Ordered Global Register values
	M8C_SetBank0
	ret


; PSoC Configuration file trailer PsocConfig.asm
